Update to Gradle 7.0.2
xtomlj/xtomlj pull request #8
Opened 2021-05-20 18:33 UTC by A248

A lot of parts of the build had to be updated to be compatible with Gradle 7. In addition to making the build Gradle 7 compatible, I also replaced use of deprecated methods in Gradle 7 which will be removed in Gradle 8 (which is hopefully a long time from now)

Here's a list of changes:

* `api` and `implementation` replace `compile` when specifying dependencies
* spotless-gradle-plugin, errorprone, the errorprone plugin, and the license-report plugin are all updated
* Maven central is used instead of jcenter
* destinationDir, classifier, and baseName are replaced with the non-deprecated destinationDirectory, archiveClassifier, and archiveBaseName options. I checked to ensure `archiveBaseName.get()` still produces "xtomlj".

This makes the build functional on JDK 16, enhances the dependency metadata for Gradle dependents, and opens up more possibilities for xtomlj in general.

Related to this, would you like to run the Github Actions Gradle workflow on JDK 11 and 16 in addition to 8? I'll make a separate PR for it.

2021-05-20 21:12 UTC, kPYKx7Ddw4n1aIKZ requested changes
Looks fine for the most part.

2021-05-20 21:12 UTC, kPYKx7Ddw4n1aIKZ commented on build.gradle
> -    excludedPaths '.*/generated-src/.*'
Are you sure that we should remove this line?
This looks like it is excluding ANTLR generated code from static analysis.

I don't think there's much we can do if something is wrong there.

2021-05-20 22:10 UTC, A248 commented on build.gradle
> -    excludedPaths '.*/generated-src/.*'
I'll re-add this.

I previously thought `disableWarningsInGeneratedCode` would cover it. However, looking inside the generated code, it seems that `@Generated` is not added by antlr, and this is confirmed by these open issues:
https://github.com/antlr/antlr4/issues/2512
https://github.com/antlr/antlr4/issues/2568

2021-05-20 23:55 UTC, A248 commented
Fixed a few things - should be ready now.

2021-05-21 10:22 UTC, kPYKx7Ddw4n1aIKZ commented
👍

2021-05-21 10:22 UTC, merged